### ISSUE TITLE
Tag with object instead of string

### ISSUE THREAD

**Issue by solace** [radiac/django-tagulous#103]
Hello,

Not sure if I've missed this in the documentation somewhere, but is it possible to use objects instead of strings for tags? eg. A tag field containing a list of users/FKs.

Thanks

**Comment by radiac** [comment]
It depends what you're trying to achieve. Tagulous is essentially a wrapper around ForeignKey and ManyToManyField to let you assign strings instead of objects - behind the scenes it creates objects out of the strings.

If you want to select from a list of existing objects with autocomplete, you might want to look at something like django-select2.

If you want to select or create objects from what's typed in, you can specify a custom TagModel to use; the string typed into the field will be put on the `name` attribute, and you can then add as many fields as you want. However there's no way to set additional attributes from the text input, so the other fields will need to be nullable or have defaults for someone to go through and fill out later through a different interface.

See [this example](http://radiac.net/projects/django-tagulous/documentation/usage/#example_custom_tag_model) for how to use a custom tag model.

**Comment by solace** [comment]
@radiac thanks.

What I’m trying to do is a cross between tags and likes.

The scenario is that a user can add an object to a number of collections. When it is added to a collection that user will be programmatically marked as ‘liking’ the object.

The more collections they add it to, the more weighted the ‘like’. Conversely, if they remove the object from collections, it won’t ‘unlike’ the object until it is removed from the last collection.

The need for count tracking makes select2 unsuitable, and other ‘liking’ mechanisms are just toggles with no counter. As the tags would be updated programmatically, I wondered if a custom TagModel would work.

However, as you suggest, even if I add a property for the user in the custom TagModel, it sounds like I can’t use it to .add a user instance if it only accepts a string, unless I use signals or override the save to convert the string (id, perhaps) into the user object, is that right?

Let me know if I have that right, or if I have overlooked something in your implementation that may actually make this possible.

If I have that correct, then the alternative would be to fork this off to modify the tag manager to accept an object with a custom TagModel, as your functionality is pretty much what I need, just not only with strings.

Thank you. :)

**Comment by radiac** [comment]
Tbh I'm finding it a bit tricky to understand without some more context and code to see, but my gut feeling is that tagulous isn't going to be a good fit for this problem.

It sounds like your items are created first, and are then added to collections separately? That would put the tag field on the collection and make the item the tag model. The count stored on the item would be total number of collections it's added to, not per user. If that's what you're after then we're ok so far, but if you want the count to be specific to a user, tagulous is probably not what you want.

Tagulous also expects to be able to create new items based on the string which is typed into its field. This is a core feature, and if you don't want this then tagulous is definitely not what you want.

Tagulous takes the standard object-based M2M field and then spends almost 10,000 lines making it support assigning and returning arbitrary text strings. If you don't want to assign strings, you'd be taking a frankly over-engineered project and adding a layer of additional complexity to remove functionality - better to go the other way and put things on top of the standard M2M.

My assumption is that you want an M2M between Item and Collection, then either:

* `Collection.user` is the owner of the collection; or
* Collections are global, and multiple users can add to one collection, in which case the user object is stored on the m2m's through model.

In either scenario, you want a count for how many collections a specific user has put a specific item

If so, tagulous is not going to give you the count you need in either scenario - the counter would be on the item model, so would be global. I'd start by writing a queryset method with a `Count` aggregation.

That's probably all you need, but if you really need a cached count field, you probably want a new M2M between user and item, with the count on the through model; update that by calling the queryset method or similar after each form save.

If I've totally missed the point, do point at some code for me to see what's going on!

**Comment by solace** [comment]
My apologies for the delay in response. But you're quite right. This isn't something that tagulous will be a good fit for, and would be much simpler to implement a bespoke solution for.

I appreciate you taking the time to think through my scenario. :)
