### ISSUE TITLE
Upgrade to Select2 version 4

### ISSUE THREAD

**Issue by techdragon** [radiac/django-tagulous#11]
Can we upgrade select2 to version 4?
It looks as though it now supports defining a list of characters to stop parsing on eliminating some of the need for your monkeypatching. 

I tried to modify your adapter code, but the significant changes in version 4 of select2 left me completely unable to work out how to update your adapter.

**Comment by radiac** [comment]
I did look at adding a v4 select2 adaptor for the last version of tagulous, but as you say it's totally different to v3. I planned to write a v4 adaptor before anyone noticed, but the past few months have been very busy and I've got way behind with my open source projects. I hope to get some time over the next few weeks to get the next version of tagulous out; I'll make sure that has a v4 adaptor.
