### ISSUE TITLE
changelog autdated and supported Django version

### ISSUE THREAD

**Issue by jedie** [radiac/django-tagulous#112]
I just see v1.1.0 release today! Great!

It seems that the changelog is not up-to-date: http://radiac.net/projects/django-tagulous/documentation/upgrading/#changelog
btw, it's hard to find. (For this i made https://github.com/radiac/django-tagulous/pull/113 )

The interesting question is: What Django version is really supported, now?!?
README says just: 

> Supports Django 2.2 and later, on Python 3.6 and later.

But the "max supported" version is also interesting.
Does the new release contains https://github.com/radiac/django-tagulous/pull/104 ?

In my projects i add something like this:

![grafik](https://user-images.githubusercontent.com/71315/101283325-db344980-37d9-11eb-8d70-4832cf16b1a7.png)

**Comment by radiac** [comment]
Thanks! Yes I'm having problems with my doc builder today - the changelog is in the repo https://github.com/radiac/django-tagulous/blob/develop/docs/upgrading.rst#110-2020-12-06 - will get the builder working again asap.

Good point on an explicit version support list. I'll look at adding something like that too.
