### ISSUE TITLE
Support for full text auto complete

### ISSUE THREAD

**Issue by dany-nonstop** [radiac/django-tagulous#114]
Hi, @radiac,

Happy New Year!

In a project we currently work on, sometimes it's necessary to match the autocomplete within any part of the tag, not only start of the tag, therefore I would like to see if you're willing to add a new option? I have contributed the code with a pull request here but have not got any advice from you so far. https://github.com/radiac/django-tagulous/pull/102

It seems the contributed code to make tagulous compatible with python3 is no longer necessary, but the change to add "autocomplete_fulltext" option is still valid. As I didn't get any response from you, I'm not sure how I could contribute to your project? 

Many thanks!

**Comment by radiac** [comment]
Thanks, this is now merged! The option is now `autocomplete_view_fulltext` to reflect it's for use with the autocomplete view, as select2 should already handle this when embedding all tags in the page without the view
