### ISSUE TITLE
Feature request: commands to merge/move tags?

### ISSUE THREAD

**Issue by BoPeng** [radiac/django-tagulous#117]
I am evaluating django-tagulous for my Django website and I am wondering if there is an easy way for tag management. For example, if a user creates a new tag that is similar enough to an existing tag, or should have been in a category, something like
```
python manage.py merge_tags apple  --to Apple
python manage.py move_tag apple --category fruit
```
would be convenient to have,

A quick google search shows [this command for [django-tagit](http://yuguangzhang.com/blog/merge-tags-with-django-taggit/).

**Comment by radiac** [comment]
Tagulous doesn't have a management command for that, but if you register the tag model with Django admin, the changelist view has an action for it (check the tags to merge, select merge in the action drop-down):

https://radiac.net/projects/django-tagulous/documentation/admin/#managing-the-tag-model

**Comment by BoPeng** [comment]
Thank you very much for you quick response and I should have read the manual more thoroughly. I have some other features in mind, for example tags with categories and versions (e.g. `language:Python==3.7`) and displays of categories by color (ignore the `language`part), but I will ask later after reading more about this wonderful project.

**Comment by radiac** [comment]
That's interesting - tagulous doesn't support those out of the box, but does support nested tags; the equivalent would be `language/python/3.7`. You could then set colours with a custom tag model.

I'll add custom tree syntax to the to-do list, that would be a nice feature (probably not one I'll get to for a while though)

**Comment by BoPeng** [comment]
The main idea is that users should not have to input `language` manually. When they input `python`, and if the system has `language/python` and `snake/python`, users should be able to select one of the existing ones and the tag will be displayed as `python` with category presented by color. Then if they just enter `python`, the admin or the system should assign a category... 

If I can somehow control what the user need to type and will see, the internal presentation of tags does not matter,  `language/python` is just as good as `language:python`.
