### ISSUE TITLE
Extra parameter to autocomplete view

### ISSUE THREAD

**Issue by BoPeng** [radiac/django-tagulous#119]
I plan to use tags such as `input:format1` and `output:format2` internally in one `TagField` since there can be more categories in the future and I do not want to create a `TagField` for each of them.

Then I would like to hide this implementational details from users, so I create, conceptually separate fields for different categories

```
input = tagulous.forms.TagField(autocomplete_tags = get_all_input_tags_without_prefix() )
output = tagulous.forms.TagField(autocomplete_tags = get_all_output_tags_without_prefix() )
```
and there are two tag fields in the form.

Now, I am confused with the role of `autocomplete_tags` and autocompletion views,

1. If I provide `autocomplete_tags`, will the frontend also call an autocompletion view? I suppose if there are not many tags, I can supply all of them to the frontend and save a few AJAX calls to the backend.
2. If I would like to make use of an autocompletion view, does `autocomplete_tags` even matter? Also, how can I let the backend know which field is being filtered? I mean, when the user enters tag in the `input` field, the backend needs to 
   * Know which category the field is for (`input` in this case). <--- missing piece
   * Find all matching tags, strips the category part, and return. In this way users will never see or have to enter the `input:` part.

**Comment by radiac** [comment]
`autocomplete_tags` is for when you don't have enough tags to justify the effort and overhead of a separate view with ajax calls. It will be ignored when `autocomplete_view` is set.

I'm not entirely clear on what you're trying to achieve; it sounds like you need to keep the tags separate, so I'd probably reconsider separate tag models if you can.

There's no built-in way to pass extra info alongside the tag name to the frontend, and that feels like the wrong way to solve it - at that point it feels like you'd not be dealing with a tag, you're dealing with more of a straightforward FK/M2M field, so it would be outside tagulous's remit.

If you want to stick with tagulous and use a shared tag model, you could filter tags in an autocomplete view by using different views for each field?

**Comment by BoPeng** [comment]
> autocomplete_tags is for when you don't have enough tags to justify the effort and overhead of a separate view with ajax calls. It will be ignored when autocomplete_view is set.

Great. Thank you for your clarification. So in the worst case I can simply pass everything through `autocomplete_tags`.

> tags in an autocomplete view by using different views for each field?

Using different views for each field is possible for me. How do I specify it from the `Form`? 

```
TagField(
    tag_options = .... autocomplete_view = ....field_specific_view )?
```

**Comment by radiac** [comment]
Yes, you'd set the `autocomplete_view` on the field, then register multiple views, or one view at multiple urls. See the [Autocomplete AJAX Views example](https://radiac.net/projects/django-tagulous/documentation/usage/#example_autocomplete_views), and "Filtering an autocomplete view".

**Comment by BoPeng** [comment]
That is exactly the problem I had, because only one view is specified in, say, `Person.skill`.

```
class Person(models.Model):
    name = models.CharField(max_length=255)
    skills = tagulous.models.TagField(
        autocomplete_view='person_skills_autocomplete'
    )
```
In my case `skills` can be `work:write_report`, `personal:fishing`, `personal:boat` etc, and in my form I have

```
personal_skills = tagulous.forms.TagField()
work_skills = tagulous.forms.TagField()
```
and I would like these two fields to use different view function (or pass different options). So iI am wondering how to pass different `autocomplete_view` to `forms.TagField`, not `models.TagField`.

**Comment by BoPeng** [comment]
According to 

https://github.com/radiac/django-tagulous/blob/93521114a67b11e3a8cd80b4b4267ca11cde514b/tagulous/forms.py#L36

It looks like

```
personal_skills = tagulous.forms.TagField(
    tag_options = {'autocomplete_views': personal_specific_view}
)
```

Let me try it.

**Comment by radiac** [comment]
I was about to suggest that! Looks like it should work but [the docs](https://radiac.net/projects/django-tagulous/documentation/tag_options/#form_options) are missing that option

**Comment by BoPeng** [comment]
Then a perfect solution for me would be an additional parameter `autocomplete_kwargs`, which is called as

```
                attrs["data-tag-url"] = reverse(autocomplete_view, autocomplete_kwargs)
```
and would allow
```
work_skills = tagulous.forms.TagField(
    tag_options = {'autocomplete_views': general_view, `autocomplete_kwargs': {'category': 'work'}}
personal_skills = tagulous.forms.TagField(
    tag_options = {'autocomplete_views': general_view, `autocomplete_kwargs': {'category': 'personal'}}
)
```

I know this sounds like a very unique use case but in general I think allowing additional parameters to `autocomplete_view` can be useful for things like number of items to return.

**Comment by BoPeng** [comment]
There is a `AUTOCOMPLETE_SETTINGS`, checking what it is used for ...

**Comment by radiac** [comment]
Yeah, I can see an `autocomplete_view_kwargs` (and probably matching `autocomplete_view_args` ) would make it more complete, although I wonder if it would be cleaner to support passing a url as `reverse_lazy` - there are already so many options!

I won't get onto that for a while - PR would be welcome, but in the meantime you could just add the kwargs in the url conf.

The settings arg there was intended for configuring the javascript control - it's passed through on the HTML field's `data-tag-options` attribute (see [settings docs](https://radiac.net/projects/django-tagulous/documentation/installation/#settings)).

**Comment by BoPeng** [comment]
So `autocomplete_settings` is passed to the frontend to be used by an adaptor, which in a majority of the cases would be `None`, right. The following patch would allow me to use that setting for my application.

```diff
diff --git a/tagulous/forms.py b/tagulous/forms.py
index fed0936..613748b 100644
--- a/tagulous/forms.py
+++ b/tagulous/forms.py
@@ -32,11 +32,19 @@ class TagWidgetBase(forms.TextInput):
     choices = None

     def render(self, name, value, attrs={}, renderer=None):
+
+        # Merge default autocomplete settings into tag options
+        tag_options = self.tag_options.form_items(with_defaults=False)
+        if self.default_autocomplete_settings is not None:
+            autocomplete_settings = self.default_autocomplete_settings.copy()
+            autocomplete_settings.update(tag_options.get("autocomplete_settings", {}))
+            tag_options["autocomplete_settings"] = autocomplete_settings
+
         # Try to provide a URL for the autocomplete to load tags on demand
         autocomplete_view = self.tag_options.autocomplete_view
         if autocomplete_view:
             try:
-                attrs["data-tag-url"] = reverse(autocomplete_view)
+                attrs["data-tag-url"] = reverse(autocomplete_view, kwargs={} if autocomplete_settings is None else autocomplete_settings)
             except NoReverseMatch as e:
                 raise ValueError("Invalid autocomplete view: %s" % e)

@@ -59,12 +67,6 @@ class TagWidgetBase(forms.TextInput):
                 )
             )

-        # Merge default autocomplete settings into tag options
-        tag_options = self.tag_options.form_items(with_defaults=False)
-        if self.default_autocomplete_settings is not None:
-            autocomplete_settings = self.default_autocomplete_settings.copy()
-            autocomplete_settings.update(tag_options.get("autocomplete_settings", {}))
-            tag_options["autocomplete_settings"] = autocomplete_settings

         # Inject extra settings
         tag_options.update({"required": self.is_required})
```

**Comment by BoPeng** [comment]
>  I can see an autocomplete_view_kwargs (and probably matching autocomplete_view_args ) 

I read somewhere that `autocomplete_view` could be a view function, or a name pattern that can be `reversed` but in implementation it only accepts a name, which makes the name `_view` a bit wrong.

Allowing the pass of an URL would also work, and I could do something like

```
personal_skills = tagulous.forms.TagField(
    tag_options = {'autocomplete_url: f'{reverse(general_view)}?category=personal' }
)
```

I am fine with any of the options and will be happy to supply a PR if you can let me know you preferred solution.

**Comment by radiac** [comment]
I reckon `autocomplete_view_args` and `autocomplete_view_kwargs` is probably the easiest way to get this working, and probably the least confusing for users trying to figure out what to do next.

That way of `autocomplete_url` would work for form fields, but if you want to set it on the model field I _think_ that would be evaluated before the urlconf is loaded. If so it would need to be a `reverse_lazy` object rather than a pre-reversed string. Think that would just lead to more confusion and mistakes.

**Comment by BoPeng** [comment]
#120 is created.
