### ISSUE TITLE
Breaks with other Django Select2 libraries

### ISSUE THREAD

**Issue by techdragon** [radiac/django-tagulous#12]
I've tried both django-easy-select2 and django-select2 and this library breaks with both of them. 
I cant get tagulous to work with any other admin select2 widgets. Compatibility would be nice. 

For what its worth, as much as I like Tagulous more, this has forced me to abandon using Tagulous on a brand new project and switch to another library with the hope I can migrate to Tagulous in future.

**Comment by radiac** [comment]
Noted! I'll put out a version of tagulous with a v4 adaptor as soon as possible.
