### ISSUE TITLE
Small hardcoded style="width: 157px;" ?!?

### ISSUE THREAD

**Issue by jedie** [radiac/django-tagulous#133]
It seems that the tag admin field has a hardcoded `style="width: 157px;"` ?!?
e.g.:
![image](https://user-images.githubusercontent.com/71315/130242278-84d17e9e-36df-46c5-9a6e-3b8c4874f418.png)

I would like to have a wider field and didn't find a way to remove or change the width values... Is there a way?

**Comment by radiac** [comment]
I think this is due to the way select2 initialises - it sets its component to the width of the element it replaces. My assumption was this should be fine, and would be consistent with the select2 that ships with Django 2+ for `autocomplete_fields`. Now you raise it though, that does look impractically small. I'll investigate what Django does with its built-in select2.

**Comment by jedie** [comment]
Hm. Okay...

Possible work-a-round by this Stylesheet:
```
.select2 {
    width: 50%!important;
}
```

**Comment by radiac** [comment]
The width of a tag field looks consistent with other fields in the example project admin under Django 3.2:

![image](https://user-images.githubusercontent.com/241712/130698776-6347d145-744e-45e6-8d9b-05ac01d87c6d.png)

I therefore think it'd make sense to leave it how it is as the default, but I think are two options for overriding:

1. Override the width with a stylesheet rule, as you've said
2. Set the `width` of the Select2 control (see their docs on [appearance](https://select2.org/appearance)) using the [`autocomplete_settings`](https://radiac.net/projects/django-tagulous/documentation/tag_options/#option_autocomplete_settings) or globally with [`TAGULOUS_AUTOCOMPLETE_SETTINGS`](https://radiac.net/projects/django-tagulous/documentation/installation/#settings). This would change the width in both admin and non-admin views though. I haven't tested this, but it should look something like:

```
myfield = TagField(... autocomplete_settings={'width': '50%'})
```

**Comment by jedie** [comment]
Think this should be added to the docs, isn't it?
