### ISSUE TITLE
How to set required=False ?

### ISSUE THREAD

**Issue by BitcoinKing** [radiac/django-tagulous#15]
How to set required=False ?
By default every field is set required=True form my Model.
Cannot find in docs where to set required=False

**Comment by radiac** [comment]
You should be able to set `tagulous.models.TagField(null=True, blank=True)` on your model field; the field in admin or a `ModelForm` should then detect that and automatically set `required=False`.

You only need to explicitly use `required=False` if you're creating a `Form`, and using the `tagulous.forms.TagField` directly.

Hope this helps. If so, we'll leave this open to remind me to update the docs for the next release.

**Comment by udanieli** [comment]
From django 1.8 (django/django@011abb7d96c75f6154c15a8a0f997d8c27698679), setting the `null` option will issue this warning:

`(fields.W340) null has no effect on ManyToManyField`
