### ISSUE TITLE
Best approach for a dropdown select instead of comma separated list?

### ISSUE THREAD

**Issue by Jihad** [radiac/django-tagulous#161]
My case is:
I have multiple type of tags, like: Skills, theme, music types..etc
each one can have up-to 20 tags. with multiple users using Django Admin to create new Posts with Tags.

We are ending up with similar redundant tags like: Football, soccer or High vs. loud...etc because of the difficulty of checking what's available quickly.

Is it possible in an easy way, when creating new "post" (from admin) to be able to select from the existing, rather than adding comma separated ones? which is causing duplication issues and forgetting about some, it's not practical.

If there is a missing tag to be added, it's fine to create it manually first from the tags page, then select it from the post create/edit page. Or even better the usually ( + ) sign shows next to the field.

Is there any recommended approach for this?

As a visual explanation, I'm looking for something close to this, or just solves the problem like it:
![drop down search](https://i.stack.imgur.com/2ixxw.png)

**Comment by radiac** [comment]
I've not done it myself, but because the TagField is based on the ManyToManyField, you should be able to get the form field to behave like a m2m again fairly easily. I'd stay by trying to replace the form field with a `MultipleChoiceField`
