### ISSUE TITLE
Autocomplete broken on Django 4

### ISSUE THREAD

**Issue by chrisdevilliers** [radiac/django-tagulous#164]
I am unable to get autocomplete working in the admin interface on Django 4. To recreate the issue, follow the `README.rst` from the `example/` directory:
1. Replace `3.2` with `4.0` in the line `pip install "Django~=3.2"`.
2. Replace `url` with `re_path` in `example/urls.py` and change the import line to `from django.urls import re_path`.
3. Go to the admin interface and add a Person.

The `Title`, `Skills` and `Hobbies` fields are normal text input widgets instead of the Javascript dropdown with autocomplete feature. See the screenshot below:
![2022-06-24-092618_1904x1017_scrot](https://user-images.githubusercontent.com/456507/175485361-63f78b91-5a92-4911-b11e-cab126a7acf8.png)

Package versions:
```
Django          4.0.5
django-tagulous 1.3.3
```

**Comment by flbraun** [comment]
@radiac Could you please take a look at this issue and the provided PRs? We have to add a lot of unstable workaround code to circumvent this issue, which is not a nice experience.

**Comment by jedie** [comment]
@radiac The fix was merged, but there is no new release made since the merge, isn't it? Can you please create a new release?

**Comment by radiac** [comment]
This is now fixed in v2.0 - thanks for your patience everyone!
