### ISSUE TITLE
Django 4.2 python 3.12 tagsfield remain empty 

### ISSUE THREAD

**Issue by engrimran7** [radiac/django-tagulous#177]
Hi support i am trying to parse all the fields in a form to tags field as tags while overriding the post save method its working fine without any issues all the fields are parsed to tags and associated to specific posts or resources checked in admin module of tagulous also. here comes a twist 

Tag fields of the posts and or resources remain empty when tried to edit the post it dhows tagsfield empty .
I am stuck in no where any expert please assist.

**Comment by radiac** [comment]
Sorry it took me so long to get to this! Unfortunately I can't recreate it - I'll close this for now, but please re-open if you can provide a simple code sample to recreate.

**Comment by engrimran7** [comment]
> Sorry it took me so long to get to this! Unfortunately I can't recreate it - it's possible whatever issue caused this is fixed in the next release. I'll close this for now, but please re-open if you can provide a simple code sample to recreate.


Thanx alot the issue was resolved
