### ISSUE TITLE
Ist this project dead?

### ISSUE THREAD

**Issue by jedie** [radiac/django-tagulous#178]
Seems that @radiac hase no time to maintain this project, isn't it?

e.g.: Small fixes like https://github.com/radiac/django-tagulous/pull/169 and https://github.com/radiac/django-tagulous/pull/167 and the other PRs are not merged and get no reactions :(

**Comment by mohmyo** [comment]
This is just a great package! 
I would like to help in maintaining it if possible

**Comment by radiac** [comment]
Tagulous v2.0.0 is finally now up on pypi! This hopefully addresses all key breaking issues and supports Django 3.2 through to 5.1.

Thanks for everyone's patience - I've had a [difficult and busy couple of years](https://radiac.net/personal/diary/2023/12/remarkably-terrible-year/), but am catching up on things now. I plan to push on with a v2.1 release soon, to mop up some of the other outstanding issues
