### ISSUE TITLE
tagulous.admin.enhance() will change the list_display to a list

### ISSUE THREAD

**Issue by jedie** [radiac/django-tagulous#183]
Think it's a bad idea to change the "list_display" of a ModelAdmin class to a list, because it's mutable and this may result in side effects.

**Comment by radiac** [comment]
That's a fair point. I'm not sure how much real world risk with it, but may as well address it in the next release. There's potential that someone could now expect it to be a list, but that'd be reasonably simple for them to change as long as it's listed in the upgrade notes.

**Comment by jedie** [comment]
Same for `get_autocomplete_fields()` ;)
