### ISSUE TITLE
autocomplete and crispy forms

### ISSUE THREAD

**Issue by ksandro** [radiac/django-tagulous#35]
I'm using django-cryspy-forms in my project. And I'm also trying to use tagulous autocomplete in my forms. It works, but form looks quite strange. Data entry field has extra borders. Maybe anybody knows if there is an easy way to fix it?

![screenshot at 2017-10-03 16-32-46](https://user-images.githubusercontent.com/6919677/31125218-90801e14-a858-11e7-92dc-57f187be4f0a.png)

**Comment by dubirajara** [comment]
I'm using cryspy-forms too, yes, has extra borders, but work fine to me:

![captura de pantalla 2017-11-25 a las 19 08 23](https://user-images.githubusercontent.com/15200556/33233304-4d67496e-d214-11e7-9e7f-7dc8360eaba5.png)

 increasing the field of form a bit, it would be fine, or changing the properties of the css _select2.css_ class _"select2-choices"_

**Comment by andytwoods** [comment]
just wondering what solution you ended up using :)

**Comment by artscoop** [comment]
@dubirajara If you have a solution for this problem, it would be greatly appreciated

**Comment by dubirajara** [comment]
hi @artscoop, Have you tried overwriting the select2.css CSS?

before overwriting css:
![captura de pantalla 2018-05-04 a las 17 56 13](https://user-images.githubusercontent.com/15200556/39637847-7ea1e736-4fc4-11e8-85c6-4cadab062e2b.png)

 to hide extra borders, for me it has worked like this, overwriting the css, in my own css, I've put it like this:
```
.select2-container-multi .select2-choices {
  background-image: linear-gradient(to bottom, #eee0 1%, #f3f3f300 15%) !important;
  border: none !important;
  background-color: transparent !important;
}
```
after overwriting css:
![captura de pantalla 2018-05-04 a las 17 50 15](https://user-images.githubusercontent.com/15200556/39637568-bc5aa88e-4fc3-11e8-85a1-9e88a1a195d6.png)

try it like this, or overwrite the select2.css to your liking.
