### ISSUE TITLE
Need help with the UI

### ISSUE THREAD

**Issue by richielo** [radiac/django-tagulous#37]
I am trying to find the way to have the UI changing effect when I press enter after inputting a tag  (which also comes with a cross to delete the tag) instead of typing comma. I saw that implemented in the example but not sure how is it done.  My model and form are as below: 

    class UserProfile(models.Model):
        ..........
        subjectTags = tagulous.models.TagField(to=SubjectTags)

    class CompleteProfileCTutorForm(forms.ModelForm):
        phone_number = forms.CharField(max_length = 12)
        bio = forms.CharField(max_length = 500, widget=forms.Textarea)
        avatar = forms.ImageField(required=False)
        subjectTags = tagulous.models.TagField()
    
        class Meta:
            model = UserProfile
            fields = [
                         'phone_number',
                        'bio',
                        'subjectTags',
                        'avatar',
                     ]
            exclude = ('user',)

Thanks for your help in advance.

**Comment by radiac** [comment]
If you're not seeing the autocomplete dropdown then you may not have the css and javascript loaded; make sure that your form media is added to your header; for example: https://github.com/radiac/django-tagulous/blob/develop/example/example/templates/example/index.html#L3-L8

Once you've got that you should get the autocomplete dropdown, and can select tags from there. However, typing a comma will always create a new tag; if you want to create a tag with a comma in it, you will need to wrap the tag with quote marks, eg `"tag, with, commas"`

**Comment by richielo** [comment]
I tried adding the the lines you highlighted in the template but it didn't work. What I meant is how do I replicate the behaviour like in the first section of the demo, which when I press enter it becomes a tag with a cross to remove it. Right now, it's just a command separated string in the UI.

![sc](https://user-images.githubusercontent.com/13329406/32358832-16434b3c-c084-11e7-999b-f28a557b88a9.png)

**Comment by radiac** [comment]
Sorry for the delay, missed your reply. This looks like your javascript isn't loading properly, but there could be many reasons for that. Use your web browser's inspector to check that the files are included in the html source (if they're not it indicates a problem with your form or template), and that they're downloaded successfully (it might be an issue with your static files).
