### ISSUE TITLE
TagRelatedManagerMixin causing extra database queries

### ISSUE THREAD

**Issue by matthiaswh** [radiac/django-tagulous#42]
When I loop over a list of objects that have a tag field, the [reload method](https://github.com/radiac/django-tagulous/blob/032adc000d46983f03509e1667d75cf863f0b1f4/tagulous/models/managers.py#L486) in TagRelatedManagerMixin is triggering a database lookup for every object.

Example of the query:

```

SELECT "games_location"."id", "games_location"."name", "games_location"."slug", "games_location"."count", "games_location"."protected", "games_location"."title", "games_location"."content" FROM "games_location" INNER JOIN "games_game_location" ON ("games_location"."id" = "games_game_location"."location_id") WHERE"games_game_location"."game_id" = '8'  Duplicated 7 times. | 4.349717268377556% | 0.50 | SelExpl

...

E:\vm\venv\churchworthy\lib\site-packages\tagulous\models/managers.py in reload(486)   
self.tags = list(self.all())

```

Because `self.all()` is being forced into a list, it's executing the query for each Game object. Normally I would use `prefetch_related()` to cut down on database calls but this is preventing it from actually helping. I'm not totally clear on what the reload method does for me when I'm just querying tags and not saving anything.

**Comment by ojh** [comment]
I'm noticing this too. @matthiaswh - did you find a suitable explanation/solution/workaround for this?

**Comment by aldoushuxley** [comment]
Anyone figure a workaround for this? Unnecessarily duplicating queries is not ideal. Surely there's a relatively straight forward way of overriding this behaviour?
