### ISSUE TITLE
Support: Using Tagulous in a Form (not ModelForm)

### ISSUE THREAD

**Issue by apollodatasolutions** [radiac/django-tagulous#44]
Maybe I am too dense, but I went over the documentation a few times and I cannot find how to use Tagulous in a regular Form that is not a ModelForm.  Maybe I am missing something.

We are trying to have a search view that can be filtered by tag but cannot figure out how to set it up so Tagulous autocompletes from the right field in the right model.  Anyone can point us in the right direction?

**Comment by apollodatasolutions** [comment]
We got this far, in the form:

    tags = tagulous.forms.SingleTagField(tag_options=Lead.tags.tag_options, label='Tags', required=False, help_text=_('Filter by lead tags.  You can organize leads by any tag you want.'))

But cannot figure out how to use the right autocomplete view.

**Comment by radiac** [comment]
You should be able to pass the field constructor an iterable in `autocomplete_tags` - from there you can use autocomplete as normal.

http://radiac.net/projects/django-tagulous/documentation/usage/#example_form

http://radiac.net/projects/django-tagulous/documentation/forms/#form_singletagfield

**Comment by radiac** [comment]
You should be able to use the `autocomplete_view` tag option - see

* http://radiac.net/projects/django-tagulous/documentation/usage/#example_autocomplete_views
* http://radiac.net/projects/django-tagulous/documentation/views/#autocomplete_views
* http://radiac.net/projects/django-tagulous/documentation/tag_options/#option_autocomplete_view

Although the example in the first link is for a model field, you should just be able to pass `autocomplete_view` in as an argument to the field using the `tag_options` argument; the following is untested, but should put you close to the solution:

```
tags = tagulous.forms.SingleTagField(
    tag_options=Lead.tags.tag_options + tagulous.models.TagOptions(
        autocomplete_view='lead_tags_autocomplete'
    ),
    label='Tags',
    required=False,
    help_text=_('Filter by lead tags.  You can organize leads by any tag you want.'),
)
```

then add the autocomplete view with the name `lead_tags_autocomplete` based on the example in the first url.

Hope this helps!
