### ISSUE TITLE
Django 2.0 compatibility

### ISSUE THREAD

**Issue by apollodatasolutions** [radiac/django-tagulous#48]
Now that it works with 1.11, how about 2.0?  Any stopping issues?

**Comment by radiac** [comment]
I've started a new branch for 2.0 support (`feature/django-2_0`), but haven't had a chance to look at what'll be involved in the upgrade; at this point tests are failing due to the `on_delete` FK argument now being required.

**Comment by apollodatasolutions** [comment]
Ok, if I have time in the coming weeks I'll take a peek.

**Comment by dubirajara** [comment]
I use django 2.0, but for my use case at the moment I have not had any problems.

**Comment by radiac** [comment]
Django 2.0 and 2.1 now have full support in Tagulous 0.14.0 onwards
