### ISSUE TITLE
admin widget in django template

### ISSUE THREAD

**Issue by addsimm** [radiac/django-tagulous#55]
Hi again,

I have a tags = TagField( autocomplete_view='story_tags_autocomplete') field in my model.

I want to implement this widget - from the admin, in a user facing page

![screen shot 2018-08-01 at 12 22 19 pm](https://user-images.githubusercontent.com/2389450/43543672-a0d4f60c-9585-11e8-87b8-38a074d8ac04.png)
 
After having looked at the example project and the docs,  I cannot figure out how to code the template. I have also looked at the select2.js docs.  An ordinary jquery ajax call gives me the tags but from there I am stuck.

Can you add this as an example to the example?  It would look nice

Thanks

**Comment by radiac** [comment]
Are you including the form's media in your page?

https://github.com/radiac/django-tagulous/blob/master/example/example/templates/example/index.html#L3

(Can't see this anywhere obvious in the docs, so wonder if that might be the issue)

**Comment by addsimm** [comment]
Yes I looked at that but it produces the wrong widget; it seems like I need to specify the widget in the model form.  Alternatively, it seems like I could use select2:

    $('#mySelect2').select2({
      ajax: {
        url: '/example/api',
        processResults: function (data) {
          // Tranforms the top-level key of the response object from 'items' to 'results'
          return {
            results: data.items
          };
        }
      }
    });

However, in aiming the ajax call at the autocomplete view, none of the things I have tried in the process results function puts the right data into the widget

**Comment by radiac** [comment]
I haven't run into this problem since the changes, so am closing this issue. If anyone still finds it to be a problem and can provide steps to recreate, please do reopen.
