### ISSUE TITLE
Fatal division by zero (ORM) error when no tagged items exist

### ISSUE THREAD

**Issue by 4levels** [radiac/django-tagulous#59]
Hi,

I noticed I kept getting a division by zero error from the Django ORM when trying to fetch the tags with weights if no tagged items exist.  The error comes from the SQL query and is reproducible on the database level.  

```python
tags = SomeModel.tags.tag_model.objects.weight()
```
throws: `django.db.utils.DataError: division by zero`
try - catch doesn't seem to help either

```sql
SELECT (FLOOR((count*5)/(SELECT MAX(count)
```

Simply adding one tagged item solves this issue.
Rewriting the query as follows solves this issue as well (as dividing by NULL yields NULL), returning weight: NULL if no tagged items exist

```sql
SELECT (FLOOR((count*5)/(SELECT NULLIF(MAX(count), 0)
```

I'm just a Django / Python beginner so I don't really know how to address this issue properly.  As far as I can tell, NULLIF seems standard SQL syntax and does work on my local PGSQL server.

Kind regards,

Erik

**Comment by radiac** [comment]
I still wasn't able to find a scenario to recreate this, but have merged the fix anyway.

The `weight()` method is changing for Django 2.2+ to use `django.db.models.functions.Floor` - slightly concerned that without a test to prove the failure I can't be sure it won't resurface, but all the edge cases I can think of are now covered by tests, so we'll just have to see if it resurfaces in the next release for 2.2+ users.

Thanks again for the report and PR.
