### ISSUE TITLE
Case sensitivity bug in SQL query when working with PostGreSQL

### ISSUE THREAD

**Issue by 4levels** [radiac/django-tagulous#60]
Hi,

I just ran into another issue where the table name is added to the SQL query without quoting.
This causes PostGreSQL to throw fatal database errors if the table names have uppercase letters since PostGres will automatically lowercase unquoted table names.  I'm working on a legacy Django project that uses camelcase in the app folder names.  Simply renaming them is currently no solution as there seems to be no clean way to migrate.  Even simply renaming the name property in the AppConfig seems to be a show stopper.  Django itself handles this nicely (hence the table names with mixed case in the database).

A quick and simple way to resolve this is by simply adding double quotes around the table name in the SQL template as found in models.py on line 83:

```python
        # Build SQL
        template = (
            '%(floor)s((count*%(upper)d)/'
            '(SELECT MAX(count) FROM "%(table)s")'  # <-- added quotes
            ')+%(lower)d'
        )
```

Just like the other issue I reported today, these seem like quick fixes imo (but I'm no expert so I could be wrong).

Maybe I'll even dare to fork and create a PR (despite me being a total python noob).

Kind regards,

Erik

**Comment by radiac** [comment]
Thanks for the report and fix - merged.
