### ISSUE TITLE
Prevent user creation of new tags

### ISSUE THREAD

**Issue by bb-msf-dd** [radiac/django-tagulous#63]
We would like to set up our tag field such that only existing tags (defined by staff) can be selected. We do not want users to be able to add new tags. Is this possible with this library? I've read through the documentation and it's unclear to me whether this library actually supports it.

Thanks!

**Comment by radiac** [comment]
Hi! This seems to be a popular request - see https://github.com/radiac/django-tagulous/issues/7 - with limited time my focus lately has been on bugs, but it is on my todo list.

**Comment by bb-msf-dd** [comment]
Thanks much for the quick response! I hadn't seen #7, glad to hear that this is on the to-do list.
Closing since this is a duplicate.
