### ISSUE TITLE
No way to get the tag_model of only filtered objects?

### ISSUE THREAD

**Issue by panpanick** [radiac/django-tagulous#68]
In part of my app, I want to get all of the tags of a particular TagField of a model, but I don't want to get that for _every_ model of that type. I want to be able to filter them. Currently it looks like this
```
tags = Game.tags.tag_model.objects.all()
```
but what I want is something like this
```
tags = Game.approved.tags.tag_model.objects.all()
```
However, that gives an error. Since the model `Game` is tied to a Verification Manager like this
```
objects = models.Manager()
approved = VerficationManager()
```
and the VerificationManager itself does not have a `tags` field like the `Game` model does.

It is set up this way because it allows me to only grab approved `Game` models to display in the app. For instance, instead of doing 
```
Game.objects.all()
```
I can do
```
Game.approved.all()
```
and only work with the approved `Game` models. Is there a similar way to filter models when grabbing tag_models?

**Comment by radiac** [comment]
As a `TagField` is a glorified `ManyToManyField`, you can filter the tag model by whatever rule you use to filter the `VerificationManager`, across the reverse relationship.

For example, something like this could work:

```
class VerificationManager(models.Manager):
    def get_queryset(self):
        return self.model.filter(verified=True)

    def tags(self):
        return self.model.tags.tag_model.objects.filter(games__verified=True)

class Game(models.Model):
    tags = TagField(related_name='games')
    verified = models.BooleanField(default=False)
    approved = VerificationManager()
```

**Comment by panpanick** [comment]
A bit of a followup to this; I am using it like
```
tags = Game.tags.tag_model.objects.filter(game_tags__verfictation_status='approved')
```
Which is grabbing every single tag for every signal `Game` object like I want, but it is including duplicates. So if five games have the tag `action` then I would get five copies of the `action` tag when listing all of the contents in the `tags` object. Is there an easy way to filter duplicates when grabbing all tags like this?

**Comment by radiac** [comment]
Hmm, looks like there might be a bug. Just to confirm, where are you putting the `distinct()`?  Is it:
```
tags = Game.tags.tag_model.objects.filter(game_tags__verfictation_status='approved').distinct()
```
which is giving you that error?

**Comment by panpanick** [comment]
Oh, it seems like I was mistakenly trying to use `distinct()` by passing in the `tags.tag_model`. That is what was causing the error. If I just use `distinct()` without arguments then it works just fine.
