### ISSUE TITLE
calling .delete() on models with tagulous

### ISSUE THREAD

**Issue by Taniform** [radiac/django-tagulous#74]
Added tagulous on a Topic Model. when .delete() is called on the model we get the error.

 unhashable type: 'Tagulous_Topic_tags'

class Topic(models.Model):
          ----------------------------------------------------------
	tags = tagulous.models.TagField(force_lowercase=True, max_count=15, blank=True,)
		)
                  -------------------------------------------

**Comment by radiac** [comment]
Looks like you're using Django 2.2 - I haven't had a chance to release a version to support that yet. In the meantime you can use the feature branch which does have support - see #71

**Comment by mbaechtold** [comment]
Installing the branch did the trick for me. Keep up the good work, this package is really helpful!

**Comment by tomasgarzon** [comment]
Hi, is this package active? I'm updating my project to Django 2.2 and we can't use feature branch for pipenv install.

**Comment by radiac** [comment]
Thanks for the prod - sorry, it's not been as active as it should be - real life has been demanding!

Just released version 1.14.1 with Django 2.2 support.
