### ISSUE TITLE
Cannot create single character tags when using a tag tree model

### ISSUE THREAD

**Issue by mcrot** [radiac/django-tagulous#81]
I'm using tagulous version 0.14.1 and the following tag model (inside an app called "manager"):
```python
import tagulous.models as tm
class TagModel(tm.TagTreeModel):
    class TagMeta:
        force_lowercase = True
```
During testing my app I see the following behaviour (on sqlite database):

I can create the tags `projects/ABC` and `projects/AB` without problems. The resulting tags
in the database are: `['projects', 'projects/AB', 'projects/ABC']`.

Then, if I try to create the tag `projects/A` (only a single character label `A`), the library
tries to generate `projects` which is already there:

```
IntegrityError: duplicate key value violates unique constraint "manager_tagmodel_name_key"
DETAIL:  Key (name)=(projects) already exists.
```

Or, when starting fresh without any tags, the statement
```python
TagModel.objects.create(name='projects/A') 
```
only creates the tag `projects`(without `A`). Is this expected behaviour?
I would expect that `projects/A` is a tag like `projects/ABC`.

**Comment by radiac** [comment]
Finally merged - thanks for the excellent patch, and once again sorry for the delay! This will be in the next release.
