### ISSUE TITLE
TagField and django tastypie POST resource is not saving m2m relationship.

### ISSUE THREAD

**Issue by slackmart** [radiac/django-tagulous#9]
Actually, I'm trying to save a tastypie model resource which contains a `TagField` from django-tagulous

Here are my model, and resources:

```
# models.py
class SimpleModel(models.Model):
    topics = tagulous.models.TagField()
    title = models.CharField(max_length=100)


# resources.py
class TopicResource(ModelResource):
    class Meta:
        queryset = SimpleModel.topics.tag_model.objects.all()
        authentication = Authentication()
        authorization = Authorization()


class SimpleModelResource(ModelResource):
    tags = fields.ToManyField(TopicResource, attribute='topics', full=True, null=True)

    class Meta:
        queryset = SimpleModel.objects.all()
        authentication = Authentication()
        authorization = Authorization()
```

the curl part:

```
curl --request POST --dump-header - --header 'Content-Type: application/json' --data '{"tags": ["/api/v1/topic/1/"], "title": "A bad dream"}' localhost:8000/api/v1/simplemodel/
```

The shell doesn't return any error, however, the tags are not associated with the new object.

By overriding the `ModelResource save_m2m method`, before the `super` call the tag object is present (print bundle.data['tags']), then in the `super(SimpleModelResource, self).save_m2m(bundle)` tastypie looks for the related manager associated with the `tags` field, the `related_mngr` is returned but when it is evaluated using: `if not related_mngr` it evaluates to `True` skiping the m2m association.

I'm sorry if it isn't an issue for this repository, I'm was not sure, and maybe it must be posted in the django-tastypie repository.

**Comment by radiac** [comment]
Thanks for the detailed report! I think this is the best place for it at the moment - it would probably be best if we can figure out a way to fix it from within tagulous. I'll take a look at it asap to see if there's anything we can do.

**Comment by sgmart** [comment]
As the docs are saying: https://docs.python.org/2/library/stdtypes.html#truth-value-testing, when tastypie code: https://github.com/django-tastypie/django-tastypie/blob/master/tastypie/resources.py#L2422 is executed, the `related_mngr` object has a `__len__` method defined: https://github.com/radiac/django-tagulous/blob/master/tagulous/models/managers.py#L256, so the `if not related_mngr` is evaluated to `True` and tastypie skip the m2m association.

**Comment by radiac** [comment]
I believe this should now be fixed.
