### ISSUE TITLE
RecursionError when evaluating a SingleTagField

### ISSUE THREAD

**Issue by trevoriancox** [radiac/django-tagulous#96]
After upgrading to Django 2.2 and Python 3.6, I am getting a RecursionError when I try to evaluate a SingleTagField (i.e. x = self.mysingletagfield).

I can see in the code how it recurses, but I'm not sure what normally stops that from happening:
 
```
# SingleTagDescriptor.__get__ calls manager.get() if instance specified.
        return manager.get() …

# SingleTagManager.get returns self.get_actual() if not changed:
            return self.get_actual() …

# SingleTagManager.get_actual calls self.descriptor.descriptor.__get__
                value = self.descriptor.descriptor.__get__(self.instance) …

# SingleTagDescriptor.__get__ calls manager.get() 
        return manager.get() 

```

**Comment by radiac** [comment]
I've not run into this before - can you give more details of where you'd call `x = self.mysingletagfield` from? Is it when the model is being saved (ie in ``.save()``), or before or after it's saved?

**Comment by trevoriancox** [comment]
I'm calling it long after the tag has been created, from a model that is not new (I'm updating the parent model but not updating the singletagfield).

**Comment by radiac** [comment]
When you say you're updating the parent model, can you give a rough code example of what you're doing so I can recreate it?

For example, is this close? If so, where would the error appear?
```
class MyModel(models.Model):
    name = models.CharField(max_length=200)
    title = tagulous.models.SingleTagField()

obj = MyModel.objects.create(name="alex", title="mr")
obj.name = "bob"
obj.save()
print(obj.title)
```

Also, do you still see the problem with the yet-to-be-released next version?

    pip uninstall django-tagulous
    pip install -e git@github.com:radiac/django-tagulous.git#egg=django-tagulous

**Comment by radiac** [comment]
I still can't recreate this one, so I'll close it. If anyone can provide steps to recreate, please feel free to reopen.
